package com.cc.three.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "build")
public class ConfigurationParts {

	// keys
    @DynamoDBHashKey(attributeName = "buildId")
    @DynamoDBAutoGeneratedKey
    private String buildId;
    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    // parts
    @DynamoDBAttribute(attributeName = "case")
    private String case_pc;
    @DynamoDBAttribute(attributeName = "casefan")
    private String case_fan;
    @DynamoDBAttribute(attributeName = "cpu")
    private String cpu;
    @DynamoDBAttribute(attributeName = "cpucooler")
    private String cpu_cooler;
    @DynamoDBAttribute(attributeName = "gpu")
    private String gpu;
    @DynamoDBAttribute(attributeName = "harddrive")
    private String harddrive;
    @DynamoDBAttribute(attributeName = "motherboard")
    private String motherboard;
    @DynamoDBAttribute(attributeName = "powersupply")
    private String powersupply;
    @DynamoDBAttribute(attributeName = "ram")
    private String ram;
    
}
