package com.cc.three.model.parts;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

public class PcPart {

    @DynamoDBHashKey(attributeName = "partId")
    @DynamoDBAutoGeneratedKey
    private String partId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;
    
    @DynamoDBAttribute(attributeName = "rating")
    private String rating;

    @DynamoDBAttribute(attributeName = "rating_count")
    private int rating_count;

    @DynamoDBAttribute(attributeName = "price_usd")
    private float price_usd;
}
