package com.cc.three.model.parts;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.cc.three.model.User;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class PcPart {

    @DynamoDBHashKey(attributeName = "name")
    private String name;
    
    @DynamoDBAttribute(attributeName = "rating")
    private String rating;

    @DynamoDBAttribute(attributeName = "rating_count")
    private int rating_count;

    @DynamoDBAttribute(attributeName = "price_usd")
    private float price_usd;
}
